# Generated by Django 3.0.3 on 2020-03-06 05:25

import dec_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0002_auto_20200229_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='rel_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=dec_app.models.images_upl)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dec_app.Category_table')),
            ],
        ),
    ]
