# Generated by Django 3.0.3 on 2020-03-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0003_rel_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rel_pro',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
