# Generated by Django 3.0.3 on 2020-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0004_auto_20200316_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='rel_pro',
            name='dates',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rel_pro',
            name='no_days',
            field=models.IntegerField(default=0),
        ),
    ]
