# Generated by Django 3.0.3 on 2020-03-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0004_auto_20200316_0611'),
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('rel_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dec_app.rel_pro')),
            ],
        ),
        migrations.AddField(
            model_name='carts',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='cart_app.CartItem'),
        ),
    ]
