# Generated by Django 3.0.3 on 2020-03-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_auto_20200319_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='rel_product',
            new_name='product',
        ),
    ]
