# Generated by Django 3.0.3 on 2020-03-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0004_auto_20200316_0611'),
        ('cart_app', '0003_auto_20200319_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='items',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='rel_pros',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_app.carts'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dec_app.rel_pro'),
        ),
    ]
