# Generated by Django 3.0.3 on 2020-04-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200403_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_str',
        ),
        migrations.AddField(
            model_name='payment_stripe',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
