# Generated by Django 3.0.3 on 2020-03-26 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200326_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='zipcode',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='firstname',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
