# Generated by Django 3.0.3 on 2020-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdefaultaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=1000),
        ),
    ]
