# Generated by Django 3.0.3 on 2020-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraddress_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='defalut',
            field=models.BooleanField(default=False),
        ),
    ]
