# Generated by Django 3.0.3 on 2020-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200405_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Str_date', models.CharField(max_length=100)),
                ('End_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='End_date',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='Str_date',
        ),
    ]
