# Generated by Django 3.0.3 on 2020-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200405_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_pro',
            name='order_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
