# Generated by Django 3.0.3 on 2020-03-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0004_auto_20200316_0611'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, max_length=100),
        ),
        migrations.CreateModel(
            name='cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dec_app.rel_pro')),
            ],
        ),
        migrations.AddField(
            model_name='carts',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='carts.cart_item'),
        ),
    ]
